export const MODULES = [
  {
    id: 1,
    name: "Mosaïque d'images + texte",
    cat: "Média",
    desc: "Grille d'images combinée à un bloc texte. Idéal pour introductions visuelles riches ou galeries contextuelles.",
    needs: ["Images (6-9)", "Titre", "Texte", "CTA optionnel"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/4da79410-08d7-4c22-b87d-0a4146d0a744/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 2,
    name: "Statistiques + image",
    cat: "Stats",
    desc: "Mise en valeur de chiffres clés avec image. Résultats, faits marquants, Stats institutionnelles.",
    needs: ["2-4 stats (chiffre + libellé)", "Image"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/995d46db-6b41-4a98-a539-8bfd2b993ca1/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 3,
    name: "2 cartes avec image et lien (2 colonnes)",
    cat: "Navigation",
    desc: "Deux grandes cartes d'entrée avec image, titre et description. Navigation principale vers deux sous-sections majeures.",
    needs: [
      "2× Image",
      "2× Titre section",
      "2× Sous-titre",
      "2× Texte",
      "2× URL",
    ],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/589d312a-1be1-49c1-a2df-e4993501cee2/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 4,
    name: "Cartes image + texte + CTA (2 colonnes)",
    cat: "Cartes",
    desc: "Grille de cartes éditoriales avec image, texte et bouton d'action. Présenter plusieurs offres, services ou programmes.",
    needs: ["Image", "Titre", "Texte", "CTA (label + URL)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/9f711811-ccd3-4adf-a073-a574f15bef88/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 5,
    name: "Cartes de navigation avec image",
    cat: "Navigation",
    desc: "Navigation visuelle vers sous-pages. Idéal pour hubs de section avec entrées multiples.",
    needs: ["Image", "Titre", "URL"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/e1b9cb91-34f0-4bb9-8f15-67e60e41ab79/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 6,
    name: "Actualité vedette + liste d'articles",
    cat: "Actualités",
    desc: "Article mis en avant + liste d'articles secondaires. Pages actualités, blogue, événements.",
    needs: [
      "Article vedette (image, titre, extrait, date)",
      "3-5 articles liste",
    ],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/c4e0bf1d-ce61-42fe-bdb9-5f195824afdd/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 7,
    name: "Texte + mosaïque d'images",
    cat: "Média",
    desc: "Bloc éditorial textuel + mosaïque d'images. Présenter une activité, un programme, un lieu.",
    needs: ["Titre", "Texte long", "Images (3-6)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/3675ede0-3421-458b-b0e6-db8c9a968cac/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 8,
    name: "Navigation + image",
    cat: "Navigation",
    desc: "Liste de liens de navigation + image illustrative. Sous-menus, pages de section avec entrées secondaires.",
    needs: ["Image", "Liens (titre + URL)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/2b939cd7-d1b2-4c21-8bdd-3eaf8619f504/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 9,
    name: "Image + texte + CTA",
    cat: "Contenu",
    desc: "Disposition image-texte classique avec appel à l'action. Module polyvalent, utilisable pour quasi toutes les sections.",
    needs: ["Image", "Titre", "Texte", "CTA (label + URL)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/875ea19a-66e6-4012-a088-114395dd9b33/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 10,
    name: "Grille de cartes informatives",
    cat: "Cartes",
    desc: "Grille sans image, contenu textuel dense. Listes de services, avantages, critères, caractéristiques.",
    needs: ["Icône ou numéro", "Titre", "Texte court"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/374f6dc1-6a46-4541-ab66-839522308d07/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 11,
    name: "Bannière d'appel à l'action",
    cat: "CTA",
    desc: "Bannière pleine largeur avec titre accrocheur et bouton principal. Conversions, inscriptions, urgences.",
    needs: ["Titre", "Sous-titre", "CTA principal", "CTA secondaire (opt.)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/98af20a8-0e0e-48ab-998c-c556ae3417c8/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 12,
    name: "Bandeau informatif",
    cat: "CTA",
    desc: "Bandeau horizontal compact pour messages courts. Alertes, délais d'inscription, informations urgentes.",
    needs: ["Texte court", "Lien (opt.)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/15ee3239-8f37-4074-9b45-6a92e577dcbd/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 13,
    name: "Navigation latérale + contenu",
    cat: "Navigation",
    desc: "Deux colonnes : navigation fixe à gauche + contenu à droite. Sections avec plusieurs sous-thèmes reliés.",
    needs: ["Liens nav latérale", "Titre", "Contenu riche (texte, images)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/053414fe-5e36-450c-8e07-f498d32c039f/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 14,
    name: "Accordéons + contenu",
    cat: "Contenu",
    desc: "Sections dépliables. FAQ, informations détaillées, politiques, conditions, horaires détaillés.",
    needs: ["Titre section", "N× (Label + Contenu)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/f577360a-47ec-47bf-9dc0-dd7c3590f8a9/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 15,
    name: "Contenu vedette + liens",
    cat: "Cartes",
    desc: "Contenu principal mis en avant avec liens associés. Pages de programme ou d'offre principale avec ressources.",
    needs: ["Image ou média", "Titre", "Texte", "Liens associés (3-5)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/04a82e40-572f-4503-af13-874d5dc1e8bf/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 16,
    name: "Carte de contenu + Image + Accordéon",
    cat: "Contenu",
    desc: "Combinaison carte texte + image + accordéon. Pages de programme complexes avec informations détaillées.",
    needs: ["Titre", "Texte carte", "Image", "N× Accordéons"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/30c6c21b-c098-4f1d-86a6-6ebc2f3465e5/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 17,
    name: "Cartes de contenu (2 colonnes)",
    cat: "Cartes",
    desc: "Cartes textuelles en 2 colonnes sans image. Ressources, documents, entrées de même niveau hiérarchique.",
    needs: ["Icône (opt.)", "Titre", "Texte", "Lien"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/d86ad2bb-2ad9-4382-a6d0-7d2a5fdfe3b6/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 18,
    name: "Grille textuelle (3 colonnes)",
    cat: "Cartes",
    desc: "Trois colonnes de contenu textuel structuré. Comparatifs, étapes, groupes de caractéristiques ou avantages.",
    needs: ["3× (Titre + Texte)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/e9bfc191-45f1-4f35-8fb3-71291495d437/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 19,
    name: "Grille équipes / partenaires (4 colonnes)",
    cat: "Personnes",
    desc: "Grille de profils ou logos en 4 colonnes. Équipes de direction, partenaires institutionnels, membres du conseil.",
    needs: ["Photo ou logo", "Nom", "Rôle ou description"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/23b3ac12-41ee-4ebf-a60f-76316b48ac27/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 20,
    name: "Bandeau réseaux sociaux",
    cat: "Social",
    desc: "Intégration et mise en avant des réseaux sociaux. Flux Instagram, liens vers Facebook, YouTube.",
    needs: ["Titre", "Comptes sociaux (URLs)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/801c11a1-b36e-44be-899c-76a658f921cd/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 21,
    name: "Carrousel de cartes image + texte + CTA",
    cat: "Cartes",
    desc: "Carrousel horizontal de cartes avec image, texte et bouton. Collections de sports, activités parascolaires, programmes.",
    needs: ["N× (Image, Titre, Texte, CTA)"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/c7968ba7-4eaf-48d5-94c0-3814141615c7/specs/",
    linkLabel: "Maquette",
  },
  {
    id: 22,
    name: "Manquant",
    cat: "Manquant",
    desc: "Emplacement réservé pour un module non encore identifié ou à définir.",
    needs: [],
    link: "",
    linkLabel: "",
  },
];

export const HEADERS = [
  {
    id: "H1",
    name: "[Block] En-tête avec vidéo et carrousel",
    desc: "Header carrousel avec vidéo/image en arrière-plan. Réservé à l'Accueil ou aux pages vitrines majeures.",
    needs: [
      "Vidéo (URL YouTube/Vimeo) / Background Image",
      "Titre",
      "Texte",
      "CTA",
    ],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/43b62a6c-d6e1-4b07-b3b2-c46bc7e9bc07/specs/",
    linkLabel: "Maquette",
  },
  {
    id: "H2",
    name: "[Pattern] En-tête sans image",
    desc: "Header minimaliste, texte seul. Pour pages utilitaires, légales ou de second niveau où l'image n'apporte pas de valeur.",
    needs: ["Titre", "Texte"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/49ed713c-f1b8-4357-9ede-7e21c3a66c8f/specs/",
    linkLabel: "Maquette",
  },
  {
    id: "H3",
    name: "[Pattern] En-tête avec image",
    desc: "Header standard avec image illustrative. Convient à la majorité des pages de section et de contenu.",
    needs: ["Image", "Surtitre", "Titre", "Texte", "CTA"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/10bc7bd0-e33d-4d77-85e4-3e656eedc3aa/specs/",
    linkLabel: "Maquette",
  },
  {
    id: "H4",
    name: "[Pattern] En-tête pleine largeur avec badge + image",
    desc: "Header pleine largeur avec image intégrée et badge/étiquette. Pour pages de programme ou d'offre spécifique.",
    needs: [
      "Image pleine largeur",
      "Badge (ex: Études-sports)",
      "Titre",
      "Texte",
    ],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/a70aed5f-6768-44f8-8268-de8a680015f3/specs/",
    linkLabel: "Maquette",
  },
  {
    id: "H5",
    name: "[Pattern] En-tête pour introduction globale",
    desc: "Header de hub de section avec liens de navigation internes. Pour pages d'entrée qui orientent vers des sous-sections.",
    needs: ["Titre", "Texte", "Section (label)", "Liens sous-sections"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/ddf15d7a-41f3-451f-bcc4-3759ac035144/specs/",
    linkLabel: "Maquette",
  },
  {
    id: "H6",
    name: "[Pattern] En-tête sans image avec CTA",
    desc: "Header orienté conversion, sans image. Titre accrocheur + appel à l'action direct. Portes ouvertes, Admission, Camps.",
    needs: ["Surtitre", "Titre", "Texte", "CTA"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/283bab1e-dd28-487d-9c06-7af165ad8187/specs/",
    linkLabel: "Maquette",
  },
  {
    id: "H7",
    name: "[Block] En-tête avec image carrousel",
    desc: "Header avec défilement d'images. Pour pages riches en contenu visuel (sports, vie scolaire, vie à l'école).",
    needs: [
      "Carrousel d'images",
      "Surtitre",
      "Titre",
      "Description courte",
      "Tooltip",
    ],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/0ce9dd7c-b781-481d-8c4c-a080a2ce0a8d/specs/",
    linkLabel: "Maquette",
  },
  {
    id: "H8",
    name: "[Pattern] En-tête centrée pleine largeur sans image",
    desc: "Header sobre, titre centré pleine largeur, fond de couleur. Pour pages de présentation, politique, légal.",
    needs: ["Suritre", "Titre"],
    link: "https://xd.adobe.com/view/01a61cf0-b9ec-4228-a251-933dbf0369d0-54f5/screen/3672fece-a012-4f19-b54c-9d283283132f/specs/",
    linkLabel: "Maquette",
  },
];

export const CAT_COLORS = {
  Navigation: "#6366f2",
  Cartes: "#0ea5e9",
  Contenu: "#10b981",
  Média: "#8b5cf6",
  Stats: "#f59e0b",
  Actualités: "#ef4444",
  CTA: "#f97316",
  Personnes: "#ec4899",
  Social: "#1d9bf0",
  Manquant: "#94a3b8",
};

export const PAGE_STATUS = {
  draft: { label: "À faire", color: "#94a3b8", bg: "#f1f5f9" },
  mockup: { label: "Maquette", color: "#d97706", bg: "#fef3c7" },
  review: { label: "À valider", color: "#7c3aed", bg: "#ede9fe" },
  done: { label: "Approuvé", color: "#059669", bg: "#d1fae5" },
};

export const DEFAULT_PAGES = [
  // ── ACCUEIL
  {
    id: "p01",
    name: "Accueil",
    url: "/",
    notes:
      "Source : aslouis.qc.ca/ · Fusion des deux entrées primaire + secondaire",
    status: "draft",
    modules: [],
  },
  // ── NOTRE ÉCOLE
  {
    id: "p02",
    name: "Notre école — Présentation",
    url: "/notre-ecole/presentation",
    notes:
      "Source : /prescolaire-primaire/ecole/presentation/ + /secondaire/ecole/presentation/",
    status: "draft",
    modules: [],
  },
  {
    id: "p03",
    name: "Notre école — Notre vision",
    url: "/notre-ecole/vision",
    notes:
      "Source : /prescolaire-primaire/ecole/vision/ + /secondaire/ecole/vision/",
    status: "draft",
    modules: [],
  },
  {
    id: "p04",
    name: "Notre école — Pédagogie à l'ASL",
    url: "/notre-ecole/pedagogie",
    notes: "Nouveau · Regroupe plan engagement num. + progression num.",
    status: "draft",
    modules: [],
  },
  {
    id: "p05",
    name: "Notre école — Notre équipe",
    url: "/notre-ecole/equipe",
    notes:
      "Source : /prescolaire-primaire/ecole/notre-equipe/ + /secondaire/ecole/equipe/",
    status: "draft",
    modules: [],
  },
  {
    id: "p06",
    name: "Notre école — Nos pavillons",
    url: "/notre-ecole/pavillons",
    notes: "Nouveau · Iframe YouTube",
    status: "draft",
    modules: [],
  },
  {
    id: "p06b",
    name: "Notre école — Arso",
    url: "/notre-ecole/arso",
    notes: "Source: /mascotte-arso/ ",
    status: "draft",
    modules: [],
  },
  {
    id: "p06c",
    name: "Notre école — Prix et distinction",
    url: "/notre-ecole/prix-et-distinction",
    notes: "Nouveau",
    status: "draft",
    modules: [],
  },
  {
    id: "p07",
    name: "Notre école — Partenaires",
    url: "/notre-ecole/partenaires",
    notes: "Contenu à identifier + logos",
    status: "draft",
    modules: [],
  },
  {
    id: "p08",
    name: "Notre école — Protecteur de l'élève",
    url: "/notre-ecole/protecteur-eleve",
    notes: "Source : /protection-de-leleve/",
    status: "draft",
    modules: [],
  },
  {
    id: "p09",
    name: "Notre école — 75e anniversaire",
    url: "/notre-ecole/75e-anniversaire",
    notes: "BROUILLON · À confirmer avec client",
    status: "draft",
    modules: [],
  },
  // ── PRÉSCOLAIRE · PRIMAIRE
  {
    id: "p10",
    name: "Préscolaire · Primaire — Hub",
    url: "/prescolaire-primaire",
    notes: "Source : /prescolaire-primaire/ · Nouvelle entrée unifiée",
    status: "draft",
    modules: [],
  },
  {
    id: "p11",
    name: "Préscolaire · Primaire — Notre offre",
    url: "/prescolaire-primaire/notre-offre",
    notes: "Nouveau · Explication globale de l'offre",
    status: "draft",
    modules: [],
  },
  {
    id: "p12",
    name: "Préscolaire · Primaire — Options sportives",
    url: "/prescolaire-primaire/nos-sports",
    notes:
      "Source : /prescolaire-primaire/nos-sports/ · Hub + 7 sports (Basketball, Cheerleading, Club de course, Football, Golf, Hockey, Soccer)",
    status: "draft",
    modules: [],
  },
  {
    id: "p13",
    name: "Préscolaire · Primaire — Soutien aux élèves",
    url: "/prescolaire-primaire/soutien-services",
    notes: "Nouveau",
    status: "draft",
    modules: [],
  },
  {
    id: "p14",
    name: "Préscolaire · Primaire — Vie scolaire",
    url: "/prescolaire-primaire/vie-scolaire",
    notes:
      "Source : /prescolaire-primaire/ecole/vie-scolaire/ · + Activités parascolaires, CréaZone, Service de garde, Comités, Événements, Reconnaissances, Implications",
    status: "draft",
    modules: [],
  },
  {
    id: "p15",
    name: "Plan engagement numérique — Hub",
    url: "/prescolaire-primaire/engagement-numerique",
    notes: "Nouveau · Multi-cycles (Préscolaire, 1er, 2e, 3e cycle)",
    status: "draft",
    modules: [],
  },
  {
    id: "p15a",
    name: "Plan engagement numérique — Sous pages",
    url: "/prescolaire-primaire/engagement-numerique/{slug}",
    notes: "Nouveau · Multi-cycles (Préscolaire, 1er, 2e, 3e cycle)",
    status: "draft",
    modules: [],
  },
  // ── SECONDAIRE
  {
    id: "p16",
    name: "Secondaire — Hub",
    url: "/secondaire",
    notes: "Source : /secondaire/",
    status: "draft",
    modules: [],
  },
  {
    id: "p17",
    name: "Secondaire — Notre offre",
    url: "/secondaire/notre-offre",
    notes: "Nouveau",
    status: "draft",
    modules: [],
  },
  {
    id: "p18",
    name: "Secondaire — Études-sport | Basketball",
    url: "/secondaire/programmes/basketball",
    notes: "Source : /programmes/basketball",
    status: "draft",
    modules: [],
  },
  {
    id: "p19",
    name: "Secondaire — Études-sport | Cheerleading",
    url: "/secondaire/programmes/cheerleading",
    notes: "Source : /programmes/cheerleading",
    status: "draft",
    modules: [],
  },
  {
    id: "p20",
    name: "Secondaire — Études-sport | Football",
    url: "/secondaire/programmes/football",
    notes: "Source : /programmes/football",
    status: "draft",
    modules: [],
  },
  {
    id: "p21",
    name: "Secondaire — Études-sport | Soccer",
    url: "/secondaire/programmes/soccer",
    notes: "Source : /programmes/soccer",
    status: "draft",
    modules: [],
  },
  {
    id: "p21a",
    name: "Secondaire — Études-sport | Golf",
    url: "/secondaire/programmes/golf",
    notes: "Source : /programmes/golf",
    status: "draft",
    modules: [],
  },
  {
    id: "p21b",
    name: "Secondaire — Études-sport | Hockey",
    url: "/secondaire/programmes/hockey",
    notes: "Source : /programmes/hockey",
    status: "draft",
    modules: [],
  },
  {
    id: "p22",
    name: "Secondaire — Langues",
    url: "/secondaire/programmes/langues",
    notes: "Source : /programmes/langues/",
    status: "draft",
    modules: [],
  },
  {
    id: "p23",
    name: "Secondaire — Explore",
    url: "/secondaire/programmes/explore",
    notes: "Source : /programmes/explore/",
    status: "draft",
    modules: [],
  },
  {
    id: "p24",
    name: "Secondaire — Vie scolaire",
    url: "/secondaire/vie-scolaire",
    notes:
      "Source : /secondaire/ecole/vie-scolaire/ · + Classes collaboratives, Arts et spectacles, Voyages, Reconnaissances",
    status: "draft",
    modules: [],
  },
  {
    id: "p25",
    name: "Secondaire — Sports interscolaires",
    url: "/secondaire/sports-interscolaires",
    notes:
      "Source : /secondaire/nos-sports-interscolaires/ · + sous-pages par sport (Cross-Country, Flag-Football, Ultimate, Volleyball féminin)",
    status: "draft",
    modules: [],
  },
  {
    id: "p26",
    name: "Secondaire — Soutien aux élèves",
    url: "/secondaire/soutien-services",
    notes: "Nouveau",
    status: "draft",
    modules: [],
  },
  {
    id: "p26a",
    name: "Secondaire — Pédagogie à l’ASL",
    url: "/secondaire/pedagogie-a-l-asl",
    notes: "Nouveau",
    status: "draft",
    modules: [],
  },
  // ── SPORTS ET ACTIVITÉS
  {
    id: "p27",
    name: "Sports et Activités — Hub",
    url: "/sports-et-activites",
    notes: "Nouveau · Vue unifiée Prés./Prim. + Secondaire + Arsenal + Camps",
    status: "draft",
    modules: [],
  },
  {
    id: "p28",
    name: "L'Arsenal — Présentation",
    url: "/sports-et-activites/arsenal",
    notes: "NOUVELLE PAGE · Contenu entièrement nouveau à créer",
    status: "draft",
    modules: [],
  },
  {
    id: "p29",
    name: "Camps — Hub",
    url: "/sports-et-activites/camps",
    notes:
      "Source : /camps-estivaux-asl-et-arsenal-2026/ · + sous-pages par sport",
    status: "draft",
    modules: [],
  },
  {
    id: "p29a",
    name: "Camps estivaux ASL et Arsenal",
    url: "/sports-et-activites/camps-estivaux",
    notes:
      "Source : /camps-estivaux-asl-et-arsenal-2026/ · + sous-pages par sport",
    status: "draft",
    modules: [],
  },
  {
    id: "p30",
    name: "Camps relâche — Mars",
    url: "/sports-et-activites/camps-relache-mars",
    notes: "Source : /camps-de-la-relache-arsenal-2-au-6-mars-2026/",
    status: "draft",
    modules: [],
  },
  {
    id: "p31",
    name: "Camps relâche — Novembre",
    url: "/sports-et-activites/camps-relache-novembre",
    notes: "Source : /camp-de-la-relache-automnale-17-au-21-novembre-2025/",
    status: "draft",
    modules: [],
  },
  {
    id: "p32a",
    name: "Expérience Arsenal",
    url: "/sports-et-activites/experience-arsenal",
    notes:
      "Source : informations-concernant-lexperience-arsenal-8-janvier-2024/",
    status: "draft",
    modules: [],
  },
  {
    id: "p32",
    name: "Préparation physique — Arsenal",
    url: "/sports-et-activites/preparation-physique",
    notes:
      "Source : /preparation-physique-ete-2026/ · Horaire type + Groupes et tarifs",
    status: "draft",
    modules: [],
  },
  // ── PORTES OUVERTES
  {
    id: "p33",
    name: "Portes ouvertes — Hub",
    url: "/portes-ouvertes",
    notes: "Nouveau · Entrée unifiée avec question de sélection de niveau",
    status: "draft",
    modules: [],
  },
  {
    id: "p34",
    name: "Portes ouvertes — Préscolaire · Primaire",
    url: "/portes-ouvertes/prescolaire-primaire",
    notes: "Source : /prescolaire-primaire/portes-ouvertes-2026/",
    status: "draft",
    modules: [],
  },
  {
    id: "p35",
    name: "Portes ouvertes — Secondaire",
    url: "/portes-ouvertes/secondaire",
    notes: "Source : /secondaire/portes-ouvertes-2026/",
    status: "draft",
    modules: [],
  },
  // ── ADMISSION
  {
    id: "p36",
    name: "Admission — Hub",
    url: "/admission",
    notes: "Nouveau · Entrée unifiée avec question obligatoire de sélection",
    status: "draft",
    modules: [],
  },
  {
    id: "p37",
    name: "Portail admission — Préscolaire",
    url: "/admission/prescolaire",
    notes:
      "Source : /prescolaire-primaire/portail-admission/admission-prescolaire/ · 6 étapes",
    status: "draft",
    modules: [],
  },
  {
    id: "p38",
    name: "Portail admission — Primaire",
    url: "/admission/primaire",
    notes:
      "Source : /prescolaire-primaire/portail-admission/primaire/ · 6 étapes",
    status: "draft",
    modules: [],
  },
  {
    id: "p39a",
    name: "Portail admission — Identification du potentiel",
    url: "/admission/identification-du-potentiel",
    notes:
      "Source : /informations-concernant-les-activites-didentification-du-potentiel-pour-les-programmes-etudes-sport/",
    status: "draft",
    modules: [],
  },
  {
    id: "p39",
    name: "Portail admission — 1re secondaire",
    url: "/admission/1re-secondaire",
    notes: "Source : /secondaire/portail-admission/1re-secondaire/ · 4 étapes",
    status: "draft",
    modules: [],
  },
  {
    id: "p40",
    name: "Portail admission — 2e–5e secondaire",
    url: "/admission/2e-5e-secondaire",
    notes: "Source : /secondaire/portail-admission/2e-5e-secondaire/",
    status: "draft",
    modules: [],
  },
  {
    id: "p41",
    name: "Calculateur de frais",
    url: "/admission/calculateur-frais",
    notes:
      "Outil interactif · À confirmer si intégré ou redirection portail finances",
    status: "draft",
    modules: [],
  },
  // ── ESPACES PARENTS
  {
    id: "p42",
    name: "Espace parents — Hub",
    url: "/espace-parents",
    notes:
      "Source : fusion /prescolaire-primaire/espace-parents/ + /secondaire/espace-parents/",
    status: "draft",
    modules: [],
  },
  {
    id: "p43",
    name: "Espace parents — Préscolaire · Primaire",
    url: "/espace-parents/prescolaire-primaire",
    notes:
      "Source : /prescolaire-primaire/espace-parents/ · Calendrier, fin., technopéd., garde-robe, transport, matériel, cafétéria, boutique",
    status: "draft",
    modules: [],
  },
  {
    id: "p44",
    name: "Espace parents — Secondaire",
    url: "/espace-parents/secondaire",
    notes: "Source : /secondaire/espace-parents/ · Structure similaire",
    status: "draft",
    modules: [],
  },
  // ── FONDATION
  {
    id: "p45",
    name: "Fondation",
    url: "/fondation",
    notes:
      "Source : /secondaire/ecole/fondation-academie-saint-louis/ + /prescolaire-primaire/fondation-de-lacademie-saint-louis/",
    status: "draft",
    modules: [],
  },
  {
    id: "p46",
    name: "Fondation — Anciens · Anciennes",
    url: "/fondation/anciens-anciennes",
    notes: "Source : /secondaire/ecole/anciens-et-anciennes/",
    status: "draft",
    modules: [],
  },
  // ── CARRIÈRES
  {
    id: "p47",
    name: "Carrières",
    url: "/carrieres",
    notes: "Source : /carrieres/",
    status: "draft",
    modules: [],
  },
  {
    id: "p48",
    name: "Carrières — Offre",
    url: "/carrieres/{slug}",
    notes:
      "Source ex: /carriere/enseignant-e-au-parascolaire-musical-piano-secteur-prescolaire-et-primaireoffre-demploi/",
    status: "draft",
    modules: [],
  },
  // ── ACTUALITÉS
  {
    id: "p51",
    name: "Actualités — Listing",
    url: "/nouvelles",
    notes: "Source : /nouvelles/ · Articles + événements regroupés",
    status: "draft",
    modules: [],
  },
  {
    id: "p52",
    name: "Actualités — Single",
    url: "/nouvelles/{slug}",
    notes: "Actualité / Événement",
    status: "draft",
    modules: [],
  },
  //  UTILITAIRES
  {
    id: "p54",
    name: "Location de salles",
    url: "/location-de-salles",
    notes:
      "Source : /location-de-salles/ · Salle polyvalente, Espace Convivio, Atrium, Gymnases, Terrain synthétique, etc.",
    status: "draft",
    modules: [],
  },
  {
    id: "p55",
    name: "Boutique en ligne",
    url: "/boutique",
    notes:
      "Source : /boutiques-en-ligne/ · 2nd Skin, Nike Team, Comité de parents",
    status: "draft",
    modules: [],
  },
  {
    id: "p56",
    name: "Campagne de financement",
    url: "/campagne-financement",
    notes:
      "BROUILLON · Structure à valider (Présentation, Images, État, Contribution, Plan de visibilité, Marchandises)",
    status: "draft",
    modules: [],
  },
  {
    id: "p57",
    name: "Nous joindre",
    url: "/nous-joindre",
    notes:
      "Source : /nous-joindre/ · Deux pavillons (Prés./Prim. + Secondaire)",
    status: "draft",
    modules: [],
  },
  // ── FOOTER / LÉGAL
  {
    id: "p58",
    name: "Nétiquette",
    url: "/netiquette",
    notes: "Source : /netiquette/",
    status: "draft",
    modules: [],
  },
  {
    id: "p59",
    name: "Politique de confidentialité",
    url: "/politique-de-confidentialite",
    notes: "Source : /politique-de-confidentialite/",
    status: "draft",
    modules: [],
  },
];
